// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { generalSans, dmSans } from "./fonts";
import { ReduxProvider } from "@/redux/provider";
import ToastProvider from "@/lib/ToastProvider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${generalSans.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReduxProvider> {children}</ReduxProvider>
        <ToastProvider />
      </body>
    </html>
  );
}
